apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-scaler-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: node-scaler-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-scaler-clusterrole
  apiGroup: rbac.authorization.k8s.io
