apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-scaler-clusterrole
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "patch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: [""]
    resources: ["pods/eviction"]  # ✅ 新增 Eviction 權限
    verbs: ["create"]
