apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: node-scaler-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: node-scaler-sa
    namespace: default
roleRef:
  kind: Role
  name: node-scaler-role
  apiGroup: rbac.authorization.k8s.io
