apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: node-scaler-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "patch"]
