FROM golang:1.23 as builder

WORKDIR /app
COPY . .

ENV GOPROXY=https://goproxy.io,direct

RUN go mod tidy
RUN go build -o custom-scheduler .

FROM ubuntu:20.04
WORKDIR /root/
COPY --from=builder /app/custom-scheduler .

CMD ["./custom-scheduler"]
