apiVersion: apps/v1
kind: Deployment
metadata:
  name: signature
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signature
  template:
    metadata:
      labels:
        app: signature
    spec:
      containers:
      - name: signature
        image: ycair/signature-pad # 替換為你構建的前端 Docker 映像名稱
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: signature-volume

        - name: signature-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf  # ConfigMap 中的 nginx.conf 文件
      volumes:
      - name: signature-volume
        persistentVolumeClaim:
          claimName: signature-pvc

      - name: signature-config-volume
        configMap:
          name: signature-config  # 對應的 ConfigMap 名稱
---
apiVersion: v1
kind: Service
metadata:
  name: signature
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: signature
